// <auto-generated />
namespace EpamLibrary.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class genresfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genresfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201806171140173_genres fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
